src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\Email(
        message: '{{ value }} n\'est pas un email valide.',
    )]
    private ?string $Email = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Contenu = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\Column(length: 255)]
    private ?string $Telephone = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use doctrine;
use App\Entity\User;

use App\Entity\Demande;
use App\Form\DemandeDecisionType;
use App\Entity\Message;
use App\Entity\BankService;
use App\Entity\Transaction;
use App\Repository\UserRepository;
use App\Repository\CompteRepository;
use App\Repository\DemandeRepository;
use App\Repository\TransactionRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DashboardController extends AbstractController
{
    #[Route('/admin', name: 'app_dashboardAdmin')]
    public function indexAdmin(ManagerRegistry $doctrine): Response
    {
        //Liste message
        $message = $doctrine->getRepository(Message::class)->findAll();
        $demande = $doctrine->getRepository(Demande::class)->findAll();

        return $this->render('dashboard/Admin/index_admin.html.twig', [
            'controller_name' => 'DashboardController',
            'ListeMessage' => $message,
            'ListeDemande' => $demande,
        ]);
    }
    #[Route('/client', name: 'app_dashboardClient')]
    public function indexClient(ManagerRegistry $doctrine,CompteRepository $compteRepository, TransactionRepository $transactionRepository): Response
    {
        // $user = $this->getUser()->getId();
        $user = $this->getUser()->getID();
        $compte = $compteRepository->findBy(array('idUser' => $user));

        if($compte){
            $transaction = $transactionRepository->findBy(array('idCompte' => $compte[0]->getId()));
        }else{
            $transaction= null;
        }
        return $this->render('dashboard/client/index.html.twig', [
            'compte' => $compte,
            'transactions' => $transaction,
        
        ]);
    }

    // #[Route('/client/operations', name: 'app_dashboardClient_operations')]
    // public function indexClientOperations(): Response
    // {
    //     return $this->render('dashboard/client/listeOperations.html.twig', [
    //         // 'controller_name' => 'DashboardController',
    //     ]);
    // }
    // still not working

    #[Route('/client/listeDemande', name: 'app_dashboardClient_listDemandes')]
    public function indexClientListDemandes(): Response
    {
        return $this->render('dashboard/client/listeDemandeClient.html.twig', [
            // 'controller_name' => 'DashboardController',
        ]);
    }

    #[Route('/client/listeMessage', name: 'app_dashboardClient_listMessage')]
    public function indexClientListMessage(): Response
    {
        return $this->render('dashboard/client/listeMessageClient.html.twig', [
            // 'controller_name' => 'DashboardController',
        ]);
    }

    #[Route('/client/newMessage', name: 'app_dashboardClient_newMessage')]
    public function indexClientNewMessage(): Response
    {
        return $this->render('dashboard/client/newMessage.html.twig', [
            // 'controller_name' => 'DashboardController',
        ]);
    }
    
    #[Route('/client/notifications', name: 'app_dashboardClientNotifications')]
    public function indexClientNotifications(): Response
    {
        return $this->render('dashboard/client/notificationsClient.html.twig', [
            // 'controller_name' => 'DashboardController',
        ]);
    }

    #[Route('/client/NouvelleDemande', name: 'app_dashboardClienNewDemande')]
    public function indexClientNewDemande(): Response
    {
        return $this->render('dashboard/client/newDemandeCompte.html.twig', [
            // 'controller_name' => 'DashboardController',
        ]);
    }

    // #[Route('/client/NewTransaction', name: 'app_dashboardClienNewTransaction')]
    // public function indexClientNewTransaction(): Response
    // {
    //     return $this->render('dashboard/client/newTransaction.html.twig', [
    //         // 'controller_name' => 'DashboardController',
    //     ]);
    // }

    
    #[Route('/conseiller', name: 'app_dashboardConseiller')]
    public function indexConseiller(ManagerRegistry $doctrine,DemandeRepository $demandeRepository): Response
    {
        $demande = $doctrine->getRepository(Demande::class)->findAll();
        $user = $this->getUser()->getId();
         if($demande) {
            $demande = $demandeRepository->findBy(array('idConseiller' => $user));
        }else{
            $demande= null;
         } 
        return $this->render('dashboard/indexConseiller.html.twig', [
            //'controller_name' => 'DashboardController',
            'ListeDemande' => $demande,
        
        ]);
    }
    // #[Route('/conseiller/decision', name: 'app_demandeDecision', methods: ['GET', 'POST'])]
    // public function editDecision(Request $request, DemandeRepository $demandeRepository): Response
    // {

    //     if ($request->getMethod()=="POST") {
    //         $etat = $request->get('etat');
    //         $demande = $demandeRepository->find($etat);
    //         $demande->setEtat($etat);
    //         $demandeRepository->save($demande, true);

    //         return $this->redirectToRoute('app_dashboardConseiller', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->render('dashboard/indexConseiller.html.twig', [
    //         'ListeDemande' => $demande,
    //     ]);
    // }
    #[Route('/conseiller/listeDemande', name: 'app_demandeConseiller')]
    public function indexDemandeConseiller(ManagerRegistry $doctrine,DemandeRepository $demandeRepository): Response
    {
        $demande = $doctrine->getRepository(Demande::class)->findAll();
        $user = $this->getUser()->getId();
         if($demande) {
            $demande = $demandeRepository->findBy(array('idConseiller' => $user));
        }else{
            $demande= null;
         } 
        return $this->render('demande/indexConseiller.html.twig', [
            //'controller_name' => 'DashboardController',
            'ListeDemande' => $demande,
        
        ]);
    }
    #[Route('/guest', name: 'app_guest')]
    public function indexGuest(ManagerRegistry $doctrine): Response
    { 
        $bankService = $doctrine->getRepository(BankService::class)->findAll();
        return $this->render('dashboard/guest/indexGuest.html.twig', [
            'controller_name' => 'DashboardController',
            'ListeBankService' => $bankService,
        
        ]);
    }
    
 
    // public function indexClientNewProfile(): Response
    // {
    //     return $this->render('dashboard/client/monProfile.html.twig', [

            
    //         // 'controller_name' => 'DashboardController',
    //     ]);
    // }

    #[Route('/client/profile', name: 'app_dashboardClientProfile')]
    public function indexClientNewProfile(UserRepository $userRepository, CompteRepository $compteRepository): Response
    {        
        $user = $userRepository->findBy(array('id' => $this->getUser()->getId()));
        $comptes = $compteRepository->findBy(array('idUser' => $this->getUser()->getId()));
        // //  dd(count($comptes));
        // $comp = [];
        // for ($i=0; $i < count($comptes); $i++) {
            
        //     $comp[$i] = $comptes[$i]->getId();
            
        // }
        // dd(count($comp));

        return $this->render('dashboard/client/monProfile.html.twig', [
                'user' => $user[0],
                'comptes' => $comptes,
        ]);
    }
}

templates/dashboard/indexAdmin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DashboardController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Dashboard Admin{{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/siala/OneDrive/Bureau/formation PHP/Projet/projetGestiBanque/gestibanque2022/src/Controller/DashboardController.php'|file_link(0) }}">src/Controller/DashboardController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/siala/OneDrive/Bureau/formation PHP/Projet/projetGestiBanque/gestibanque2022/templates/dashboard/index.html.twig'|file_link(0) }}">templates/dashboard/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/dashboard/indexClient.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DashboardController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Dashboard client{{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/siala/OneDrive/Bureau/formation PHP/Projet/projetGestiBanque/gestibanque2022/src/Controller/DashboardController.php'|file_link(0) }}">src/Controller/DashboardController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/siala/OneDrive/Bureau/formation PHP/Projet/projetGestiBanque/gestibanque2022/templates/dashboard/index.html.twig'|file_link(0) }}">templates/dashboard/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/dashboard/indexConseiller.html.twig
{% extends 'base_conseiller.html.twig' %}
{% block title %}
	Conseiller
{% endblock %}

{% block mainboard %}
<div class="content-wrapper">
						<div class="page-header">
							<h3 class="page-title">
								<span class="page-title-icon bg-gradient-primary text-white me-2">
									<i class="mdi mdi-home"></i>
								</span>
								Tableau de bord
							</h3>

						</div>
						
						<div class="row">
							<div class="col-md-7 grid-margin stretch-card">
								<div class="card">
									<div class="card-body">

										<div class="clearfix">
											<h4 class="card-title float-left">Mes opérations
											</h4>
										</p>
										<table class="table table-hover">
											<thead>
												<tr>
													<th>Date</th>
													<th>Montant virement</th>
													<th>Etat</th>
													<th>solde</th>
												</tr>
											</thead>
											
										</table>
									</div>

								</div>
							</div>
						</div>
						<div class="col-md-5 grid-margin stretch-card">
							<div class="card">
								<div class="card-body">
									<h4 class="card-title">Vos demandes
									</h4>
									<table class="table table-hover">
										<thead>
											<tr>
												<th>Numéro Demande</th>
												<th>Date de demande</th>
												<th>Type de Compte</th>
												<th> Status </th>
											</tr>
										</thead>
										<tbody>
											<tr>
											<td>01</td>
											<td>14/12/2022</td>
											<td> Compte courant </td>
											<td>
													<label class="badge badge-danger">Pending</label>
												</td>
											</tr>

										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12 grid-margin">
							<div class="card">
								<div class="card-body">
									<div class="row">


										<h4 class=" col-6 card-title">Boites de réceptions
										</h4>
										<div class="col-6 text-end mb-2">

										
							
							
							<a class="btn btn-block btn btn-gradient-info me-2" href="{{path('app_dashboardClient_newMessage')}}">
								<span class="text-white">Ecrire un nouveau message</span>
							</a>
						
										
										</div>
									</div>

									<div class="table-responsive">
										<table class="table">
											<table class="table table-hover">
												<thead>
													<tr>
														<th>Objet</th>
													<th>Contenu</th>
													<th>Date</th>
														
													</tr>
												</thead>
												<tbody>
													<tr>
														<td>Demande Info</td>
														<td> Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en page, <br> le texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, <br> on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.</td>
														<td>
															14/12/2022
														</td>
													</tr>
												</tbody>
											</table>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>


					<div class="row">
						<div class="col-12 grid-margin">
							<div class="card">
								<div class="card-body">
									<div class="row">


										<h4 class=" col-6 card-title">Listes des demandes d'ouverture de compte										</h4>
										<div class="col-6 text-end mb-2">

										
							
							
							<a class="btn btn-block btn btn-gradient-info me-2" href="{{path('app_dashboardClient_newMessage')}}">
								<span class="text-white">Ecrire un nouveau message</span>
							</a>
						
										
										</div>
									</div>

									<div class="table-responsive">
										<table class="table">
											<table class="table table-hover">
			<thead>
				<tr align="center">
                {# <th class="fw-bold">Id</th> #}
                <th class="fw-bold">Nom et Prénom</th>
                {# <th class="fw-bold">Prenom</th> #}
                <th class="fw-bold">Email</th>
                {# <th class="fw-bold">Photo</th> #}
                {# <th class="fw-bold">Identite</th> #}
                <th class="fw-bold">Type</th>
                
                <th class="fw-bold">Date de la demande</th>
                {# <th class="fw-bold">Conseiler affecté</th> #}
                {# <th class="fw-bold">actions</th> #}
                <th class="fw-bold">Etat</th>
            </tr>
        </thead>
        <tbody>
        {% for demande in ListeDemande %}
            <tr align="center">
                {# <td>{{ demande.id }}</td> #}
                <td>{{ demande.nom }} {{ demande.prenom }}</td>
                {# <td>{{ demande.prenom }}</td> #}
                <td>{{ demande.email }}</td>
                {# <td><img style="height:auto;width:20px;" src="{{asset('uploads/photos/'~ demande.photo ~'')}}"/></td> #}
                {# <td><a href="{{asset('uploads/identites/'~ demande.identite ~'')}}" target="_blank">Telecharger</td> #}
                {# <td>{{ demande.photo }}</td>
                <td>{{ demande.identite }}</td> #}
                <td>{{ demande.type }}</td>
                
                <td>{{ demande.datedemande ? demande.datedemande|date("m/d/Y") : '' }}</td>
                {# <td>{{ demande.idConseiller ? demande.idConseiller : 'auccun' }}</td> #}
							<td class="fw-bold">{{ demande.etat }}</td> 
								
							{# {% if {{ demande.etat }}=="acceptée" %}	
							 <td class="text-success">{{ demande.etat }}</td>	
							{% if {{ demande.etat }}=="refusée" %}	
							<td class="text-danger">{{ demande.etat }}</td>
							{% else %}	
							<td class="text-primary">{{ demande.etat }}</td>
							{% endif %} #}
							{% endfor %}
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>





	{# <div class="content-wrapper">
		<div class="page-header">
			<h3 class="page-title">
				<span class="page-title-icon bg-gradient-primary text-white me-2">
					<i class="mdi mdi-home"></i>
				</span>
				Tableau de bord
			</h3>

		</div>
		<div class="row">
			<div class="col-md-4 stretch-card grid-margin">
				<div class="card bg-gradient-danger card-img-holder text-white">
					<div class="card-body">
						<img src="client/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image"/>
						<h4 class="font-weight-normal mb-3">Débit total le mois dernier
						</h4>
						<h2 class="mb-5 text-dark">15,0000</h2>

					</div>
				</div>
			</div>
			<div class="col-md-4 stretch-card grid-margin">
				<div class="card bg-gradient-danger card-img-holder text-white">
					<div class="card-body">
						<img src="client/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image"/>
						<h4 class="font-weight-normal mb-3">Crédit total le mois dernier
						</h4>
						<h2 class="mb-5 text-dark">45,6334</h2>
					</div>
				</div>
			</div>
			<div class="col-md-4 stretch-card grid-margin">
				<div class="card bg-gradient-danger card-img-holder text-white">
					<div class="card-body">
						<img src="client/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image"/>
						<h4 class="font-weight-normal mb-3">
							Dernier solde
						</h4>
						<h2 class="mb-5 text-dark">95,5741</h2>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-7 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">

						<div class="clearfix">
							<h4 class="card-title float-left">Opérations du client
							</h4>
						</p>
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Date</th>
									<th>Debit</th>
									<th>Credit</th>
									<th>Montant</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Jacob</td>
									<td>Photoshop</td>
									<td class="text-danger">
										28.76%
										<i class="mdi mdi-arrow-down"></i>
									</td>
									<td>
										<label class="badge badge-danger">Pending</label>
									</td>
								</tr>

							</tbody>
						</table>
					</div>
				</div>

			</div>
		</div>
	</div>
	<div class="col-md-5 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">Gestion de votre compte
				</h4>
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Date</th>
							<th>Debit</th>
							<th>Credit</th>
							<th>Montant</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Jacob</td>
							<td>Photoshop</td>
							<td class="text-danger">
								28.76%
								<i class="mdi mdi-arrow-down"></i>
							</td>
							<td>
								<label class="badge badge-danger">Pending</label>
							</td>
						</tr>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-12 grid-margin">
		<div class="card">
			<div class="card-body">
				<div class="row">


					<h4 class=" col-6 card-title">Boites de réceptions
					</h4>
					<div class="col-6 text-end mb-2">
						<button type="submit" class="btn btn-gradient-danger me-2">Ecrire un nouveau message</button>
					</div>
				</div>

				<div class="table-responsive">
					<table class="table">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Date</th>
									<th>Debit</th>
									<th>Credit</th>
									<th>Montant</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Jacob</td>
									<td>Photoshop</td>
									<td class="text-danger">
										28.76%
										<i class="mdi mdi-arrow-down"></i>
									</td>
									<td>
										<label class="badge badge-danger">Pending</label>
									</td>
								</tr>
							</tbody>
						</table>
					</table>
				</div>

			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-12 grid-margin">
		<div class="card">
			<div class="card-body">
				<div class="row">


					<h4 class=" col-6 card-title">Liste des demandes d'ouverture compte
					</h4>
				</div>

				<div class="table-responsive">
					<table class="table">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Nom/Prénom</th>
									<th>Date</th>
									<th>Email</th>
									<th>Type de compte</th>
									<th>Etat de compte</th>
								</tr>
							</thead>

							<tbody></tbody>
						</table>
					</table>
				</div>

			</div>
		</div>
	</div>
</div> #}

<!-- content-wrapper ends --><!-- partial:partials/_footer.html -->

<!-- main-panel ends -->
<!-- container-scroller -->
<!-- plugins:js -->
<!-- End custom js for this page -->{% endblock %}